export const ActionTypes = {
  GET_TAGS_START: "GET_TAG_START",
  GET_TAGS: "GET_TAGS",
  GET_TAGS_FAILED: "GET_TAGS_FAILED",
  GET_QUESTIONS_BY_TAG_NAME_START: "GET_QUESTIONS_BY_TAG_NAME_START",
  GET_QUESTIONS_BY_TAG_NAME: "GET_QUESTIONS_BY_TAG_NAME",
  GET_QUESTIONS_BY_TAG_NAME_FAILED: "GET_QUESTIONS_BY_TAG_NAME_FAILED",
  LOAD_MORE_QUESTIONS_START: "LOAD_MORE_QUESTIONS_START",
  LOAD_MORE_QUESTIONS: "LOAD_MORE_QUESTIONS",
};
